version: '3'

services:

  gvmd:
    image: admirito/gvmd:11
    build: gvmd
    links:
      - postgres
    environment:
      GVMD_POSTGRESQL_URI: 'postgresql://gvmduser:mypassword@postgres:5432/gvmd?application_name=gvmd'
    volumes:
      - var-run:/var/run
      - cert-data:/var/lib/gvm/cert-data
      - scap-data:/var/lib/gvm/scap-data
      - plugins:/var/lib/openvas/plugins

  postgres:
    image: admirito/gvm-postgres:11
    environment:
      POSTGRES_USER: 'gvmduser'
      POSTGRES_PASSWORD: 'mypassword'
      POSTGRES_DB: 'gvmd'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

  openvas:
    image: admirito/openvas:11
    build: openvas
    # entrypoint:
    #   - ospd-openvas
    # command:
    #   - -l/dev/stdout
    #   - -f
    volumes:
      - var-run:/var/run
      - plugins:/var/lib/openvas/plugins

  redis:
    image: redis:5.0
    # skip given entrypoint to run as root so socket works
    entrypoint: bash
    command: -c "mkdir -p /var/run/redis && exec redis-server --port 0 --unixsocket /var/run/redis/redis.sock --unixsocketperm 755"
    user: root
    volumes:
      - var-run:/var/run

  gsad:
    image: admirito/gsad:11
    links:
      - gvmd
    environment:
      GVMD_HOST: 'gvmd'
      GVMD_PORT: '9390'
    ports:
      - 3000:80

  cert-scap-sync:
    image: admirito/gvmd:11
    command: sh -c "greenbone-certdata-sync; sleep 3; greenbone-scapdata-sync"
    volumes:
      - var-run:/var/run
      - cert-data:/var/lib/gvm/cert-data
      - scap-data:/var/lib/gvm/scap-data
      - plugins:/var/lib/openvas/plugins

  nvt-sync:
    image: admirito/openvas:11
    command: greenbone-nvt-sync
    volumes:
      - var-run:/var/run
      - plugins:/var/lib/openvas/plugins

volumes:
  var-run:
  scap-data:
  cert-data:
  plugins:
  pgdata:

